--Part 1
--SELECT COLUMN_NAME, DATA_TYPE from INFORMATION_SCHEMA.COLUMNS where
--table_schema = 'techjobs' and table_name = 'job';
--
--DESCRIBE job;
--Part 2
--SELECT name
--FROM employers
--WHERE location = "St Louis City";
--Part 3

--Part 4
